import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export async function exportToPDF(currentVitals, vitalsData) {
  try {
    // Create a temporary container for the PDF content
    const container = document.createElement('div')
    container.style.width = '800px'
    container.style.padding = '20px'
    container.style.background = 'white'
    container.style.color = 'black'

    // Create header
    const header = document.createElement('div')
    header.innerHTML = `
      <h1 style="color: #06b6d4; margin-bottom: 10px;">Health Monitor Report</h1>
      <p style="color: #666; margin: 0;">Generated on ${new Date().toLocaleString()}</p>
      <hr style="margin: 20px 0; border: none; border-top: 2px solid #06b6d4;">
    `
    container.appendChild(header)

    // Add current vitals
    const vitalsSection = document.createElement('div')
    vitalsSection.innerHTML = `
      <h2 style="color: #333; margin-top: 20px;">Current Vital Signs</h2>
      <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
        <tr style="background: #f5f5f5;">
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Heart Rate</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${Math.round(currentVitals.heartRate)} bpm</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">SpO2</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${currentVitals.spO2.toFixed(1)}%</td>
        </tr>
        <tr style="background: #f5f5f5;">
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Temperature</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${currentVitals.temperature.toFixed(1)}°F</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">ECG Status</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${currentVitals.ecgStatus}</td>
        </tr>
      </table>
    `
    container.appendChild(vitalsSection)

    // Add statistics
    if (vitalsData && vitalsData.length > 0) {
      const stats = calculateStatistics(vitalsData)
      const statsSection = document.createElement('div')
      statsSection.innerHTML = `
        <h2 style="color: #333; margin-top: 30px;">Statistics (Last ${vitalsData.length} readings)</h2>
        <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
          <tr style="background: #f5f5f5;">
            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Metric</td>
            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Average</td>
            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Min</td>
            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Max</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd;">Heart Rate (bpm)</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.hrAvg}</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.hrMin}</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.hrMax}</td>
          </tr>
          <tr style="background: #f5f5f5;">
            <td style="padding: 10px; border: 1px solid #ddd;">SpO2 (%)</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.spO2Avg}</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.spO2Min}</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.spO2Max}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd;">Temperature (°F)</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.tempAvg}</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.tempMin}</td>
            <td style="padding: 10px; border: 1px solid #ddd;">${stats.tempMax}</td>
          </tr>
        </table>
      `
      container.appendChild(statsSection)
    }

    // Add footer
    const footer = document.createElement('div')
    footer.innerHTML = `
      <hr style="margin: 30px 0; border: none; border-top: 1px solid #ccc;">
      <p style="color: #999; font-size: 12px; text-align: center; margin: 0;">
        This report was generated by the IoT Heart Monitor Dashboard. Please consult with a healthcare professional for medical advice.
      </p>
    `
    container.appendChild(footer)

    // Append to body temporarily
    document.body.appendChild(container)

    // Convert to canvas
    const canvas = await html2canvas(container, {
      allowTaint: true,
      useCORS: true,
      scale: 2
    })

    // Remove temporary container
    document.body.removeChild(container)

    // Create PDF
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })

    const imgData = canvas.toDataURL('image/png')
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const imgHeight = (canvas.height * pageWidth) / canvas.width
    let heightLeft = imgHeight

    let position = 0
    const pageHeightInPx = (pageHeight * canvas.width) / pageWidth

    while (heightLeft >= 0) {
      pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight)
      heightLeft -= pageHeightInPx
      position -= pageHeightInPx

      if (heightLeft > 0) {
        pdf.addPage()
      }
    }

    // Download PDF
    pdf.save(`health-report-${new Date().toISOString().split('T')[0]}.pdf`)
  } catch (error) {
    console.error('Error generating PDF:', error)
    alert('Error generating PDF. Please try again.')
  }
}

function calculateStatistics(vitalsData) {
  const heartRates = vitalsData.map(v => v.heartRate)
  const spO2s = vitalsData.map(v => v.spO2)
  const temps = vitalsData.map(v => v.temperature)

  return {
    hrAvg: (heartRates.reduce((a, b) => a + b) / heartRates.length).toFixed(0),
    hrMin: Math.min(...heartRates).toFixed(0),
    hrMax: Math.max(...heartRates).toFixed(0),
    spO2Avg: (spO2s.reduce((a, b) => a + b) / spO2s.length).toFixed(1),
    spO2Min: Math.min(...spO2s).toFixed(1),
    spO2Max: Math.max(...spO2s).toFixed(1),
    tempAvg: (temps.reduce((a, b) => a + b) / temps.length).toFixed(1),
    tempMin: Math.min(...temps).toFixed(1),
    tempMax: Math.max(...temps).toFixed(1)
  }
}
